---
collections:
  - name: awx.awx
  - name: infra.aap_configuration
  - name: ansible.controller
    source: https://console.redhat.com/api/automation-hub/content/published/
    auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
