---
collections:
  - name: awx.awx
  - name: ansible.hub
  - name: ansible.eda
  - name: infra.aap_configuration
  - name: infra.aap_configuration_extended
  - name: ansible.controller
    version: 4.6.3 # Get from /api/v2/ X-API-Product-Version
    source: https://console.redhat.com/api/automation-hub/content/published/
    auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
