---
collections:
  - name: awx.awx
  - name: ansible.platform
    source: published
  - name: ansible.controller
    version: 4.6.3
    source: published
  - name: infra.aap_configuration
    source: https://galaxy.ansible.com

