---
- name: Add Execution Environments to controller
  hosts: localhost
  connection: local
  vars:
    aap_validate_certs: false
  collections:
    - awx.awx
    - ansible.platform
    - infra.aap_configuration


  tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: ./controller_configs
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

    - name: Add organization
      ansible.builtin.include_role:
        name: infra.aap_configuration.gateway_organizations

    - name: Add teams
      ansible.builtin.include_role:
        name: infra.aap_configuration.gateway_teams

    - name: Call gateway authenticator role
      ansible.builtin.include_role:
        name: infra.aap_configuration.gateway_authenticator

    - name: Call gateway authenticator maps role
      ansible.builtin.include_role:
        name: infra.aap_configuration.gateway_authenticator_maps
...