---
- name: Add Execution Environments to controller
  hosts: localhost
  vars:
    aap_hostname: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    aap_validate_certs: "{{ lookup('env', 'CONTROLLER_VERIFY_SSL') | default(false) | bool }}"
    aap_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    aap_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
  collections:
    - infra.aap_configuration


  tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: ./controller_configs
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

    - name: Add organization
      ansible.builtin.include_role:
        name: infra.aap_configuration._organizations

    - name: Add teams
      ansible.builtin.include_role:
        name: infra.aap_configuration.gateway_teams

    - name: Add users
      ansible.builtin.include_role:
        name: infra.aap_configuration.gateway_users

...