---
- name: Add Execution Environments to controller
  hosts: localhost
  connection: local
  vars:
    aap_hostname: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    aap_validate_certs: "{{ lookup('env', 'CONTROLLER_VERIFY_SSL') | default(false) | bool }}"
    aap_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    aap_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
  collections:
    - awx.awx
    - ansible.platform
    - infra.aap_configuration


  tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: ./controller_configs
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

    - name: Add organization
      ansible.builtin.include_role:
        name: infra.aap_configuration.organizations

    - name: Add teams
      ansible.builtin.include_role:
        name: infra.aap_configuration.teams

    - name: Add users
      ansible.builtin.include_role:
        name: infra.aap_configuration.users

    - name: Call gateway authenticator role
      ansible.builtin.include_role:
        name: infra.aap_configuration.authenticators

    - name: Call gateway authenticator maps role
      ansible.builtin.include_role:
        name: infra.aap_configuration.gateway_authenticator_maps
...