---
- name: Add Execution Environments to controller
  hosts: all
  connection: local
  vars:
    aap_validate_certs: false
  collections:
    - awx.awx
    - infra.aap_configuration
    - ansible.controller
    - ansible.platform

  pre_tasks:
    - name: Include vars from platform_configs directory
      ansible.builtin.include_vars:
        dir: ./controller_configs
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

  roles:
    - {role: infra.aap_configuration.gateway_organizations, when: aap_organizations is defined}
    - {role: infra.aap_configuration.controller_users, when: aap_user_accounts is defined}
    