= AnsibleProject

== Organize Your Repository

Setup dedicated repository for your ansible projects, which includes playbooks, roles, and inventories. You might want to have a structure like this:

.Directory Structure
[source,shell]
----
.
├── .github/workflows
├── collections
│   └── requirements.txt
├── group_vars
│   ├── all
│   ├── controller
│   ├── pah
│   └── eda
├── inventory.yml
└── controller_config.yml
----

This allows you to separate controller configurations for different environment life-cycles.

== Ansible Automation Platform

This is just the specs for my lab and really the minimum requirements to highlight Ansible Controller as Code.


== Workflow

This repo currently offers a playbook that will configure Ansible controllers based on variables defined in group_vars and/or configs directory.

=== There are two parts:

. Seed the required objects to support Controller as Code
.. Located in the configs/directory are the configs to configure credential, project, and template to keep Controller as Code in sync
. Continuous configuration as code
.. Keeps Ansible controllers in sync with code via template webhook

=== Before Seeding Controller as Code:

. Ensure inventory.yml has YOUR Ansible Controller host(s) defined
. Create a GitHub repository secret that is passed during workflow
.. name expected is CONTROLLER_PASSWORD
.. secret should be the password used to login to the controller GUI


image::https://github.com/r3dact3d/Ansible-Controller-as-Code/actions/workflows/seed-cac-workflow.yml/badge.svg[link="https://github.com/r3dact3d/Ansible-Controller-as-Code/actions/workflows/seed-cac-workflow.yml"]

NOTE: You can now check the Actions to watch/check the status of the deployment.

=== Completing the sync webhook

. Manual task currently to get webhook url and token from the Job Template in the controller UI


== Function

This will create admin credential, and a project with template to get stats from the controller.  To highlight the syncing ability from Git to Controller.

    link:https://github.com/redhat-cop/controller_configuration.git
#v1-2