---
controller_configuration_credentials_secure_logging: false
controller_credentials:
  - credential_type: Source Control
    name: prod-hr-github-token
    description: Prod-HR-CaaC project pull main credential
    inputs:
      username: <REPLACE>
      password: '<REPLACE>'
    organization: Prod-HR-CaaC

  - name: aap_admin
    credential_type: Red Hat Ansible Automation Platform
    organization: Default
    description: aap admin account
    inputs:
      host: "{{ aap_hostname }}"
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      verify_ssl: false

  - name: root
    credential_type: Machine
    organization: Default
    description: root local password
    inputs:
      username: root
      password: "{{ aap_password }}"

  - name: CaC_seed_pat
    credential_type: GitHub Personal Access Token
    organization: Default
    description: config as code seed pat
    inputs:
      token: <REPLACE>

  - name: hashivault
  description: HashiCorp Vault Secret Lookup example using token auth
  organization: Default
  credential_type: HashiCorp Vault Secret Lookup
  inputs:
    url: https://vault.example.com:8243
    token: token
    cacert: "{{ lookup('ansible.builtin.file', '/path/to/ca-certificates.crt') }}"
    api_version: v2

...