---
controller_execution_environments:
  - name: "brady-ee-rhel8"
    image: quay.io/brthomps/brady-ee-rhel8:latest
  - name: "network-ee-base"
    image: quay.io/brthomps/network-ee:latest
  - name: "terraform-ee-base"
    image: docker.io/r3dact3d/terraform-ee:1.0.2
...