---
controller_execution_environments:
  - name: "ee-aap-builder-stream"
    image: quay.io/brthomps/ee-aap-ee-builder:latest
  - name: "network-ee-base"
    image: quay.io/brthomps/network-ee:latest
  - name: "terraform-ee-base"
    image: docker.io/r3dact3d/terraform-ee:1.0.2
...