---
- name: Add Execution Environments to controller
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - infra.aap_configuration
  
  roles:
    - {role: infra.aap_configuration.organizations, when: aap_organizations is defined}