---
- name: Add Execution Environments to controller
  hosts: localhost
  connection: local
  vars:
    aap_validate_certs: false
  collections:
    - awx.awx
    - infra.aap_configuration

  pre_tasks:
    - name: Include vars from platform_configs directory
      ansible.builtin.include_vars:
        dir: ./yaml
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
  roles:
    - {role: infra.aap_configuration.controller_organizations, when: aap_organizations is defined}