---
- name: Add Execution Environments to controller
  hosts: all
  connection: local
  vars:
    aap_validate_certs: false
  collections:
    - awx.awx
    - infra.aap_configuration

  pre_tasks:
    - name: Include vars from platform_configs directory
      ansible.builtin.include_vars:
        dir: ../platform_configs
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]

  tasks:
    - name: Call dispatch role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch