---
- name: Add Execution Environments to controller
  hosts: localhost
  connection: local
  vars:
    aap_validate_certs: false
  collections:
    - awx.awx
    - infra.aap_configuration
  
  roles:
    - {role: infra.aap_configuration.organizations, when: aap_organizations is defined}