---
- name: Add Execution Environments to controller
  hosts: all
  connection: local
  vars:
    aap_validate_certs: false
  collections:
    - awx.awx
    - infra.aap_configuration

  pre_tasks:
    - name: Include vars from platform_configs directory
      ansible.builtin.include_vars:
        dir: ../platform_configs
        ignore_files: [controller_config.yml.template]
        extensions: ["yml"]
  roles:
    - {role: infra.aap_configuration.controller_settings, when: controller_settings is defined}
    - {role: infra.aap_configuration.controller_organizations, when: aap_organizations is defined}
    - {role: infra.aap_configuration.controller_labels, when: controller_labels is defined}
    - {role: infra.aap_configuration.controller_users, when: aap_user_accounts is defined}